apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-tcp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: "key-to-share-172.17.255.2"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-udp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: "key-to-share-172.17.255.2"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns 
