---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jane-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]


...