---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ken-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


...