---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: jane-role
  apiGroup: rbac.authorization.k8s.io


...