---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dave-rb
subjects:
- kind: ServiceAccount
  name: dave
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: dave-role
  apiGroup: rbac.authorization.k8s.io


...