---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dave-rb
subjects:
- kind: ServiceAccount
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dave-role
  apiGroup: rbac.authorization.k8s.io


...