apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: 
    app: web
spec:
  containers: 
  - name: web
    image: docker.io/efoshkinm/first-docker
    volumeMounts:
    - mountPath: /app
      name: app
    livenessProbe:
      tcpSocket: 
        port: 8000 
    readinessProbe:
      httpGet:
        path: /index.html
        port: 8000
  initContainers:
  - name: init
    image: busybox:1.31.1
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
